name: match_the_cards
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flame: ^1.21.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  hive_ce: ^2.7.0+1
  hive_ce_flutter: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
